[WIP][Feature][LineChart] Add main source, need review
dooboolab/dooboo-ui-native pull request #227
Opened 2020-07-02 10:52 UTC by filoscoder

## Description

First commit,
Created a new branch, added the main code of LineChart feature. Not finished yet, still wip need reviews & feedback for refactoring.

## Tests
 The test code is not written yet, I will proceed after review & feedback

## Checklist

Before you create this PR confirms that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide](https://github.com/dooboolab/dooboo-ui/blob/master/CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] Run `yarn test` or `yarn test -u` if you need to update snapshot.
- [x] Run `yarn lint`
- [x] I am willing to follow-up on review comments in a timely manner.

2020-07-02 10:57 UTC, hyochan commented on package.json
> +    "react-native-svg": "^12.1.0"
Please remove the dependencies in the root! Only `dooboolab-welcome` is permitted here.

2020-07-02 10:59 UTC, hyochan requested changes
Please move your packages to `packages/` instead of `main/`. Your library would rely on separate packages as `@dooboo-ui/charts`. More information in #194 

There will be `BarChart`, `LineChart`, and `PieChart` in `@dooboo-ui/charts`. Also, don't forget to rebase this.

2020-07-06 05:31 UTC, filoscoder commented
Fixed requested changes and re-requested review. Please check the changes and let me know if it needs more updates.

TODO:
* Test-code not written yet

2020-07-07 07:50 UTC, filoscoder commented
Request a review @hyochan before merge!

2020-07-08 15:45 UTC, hyochan commented on packages/Charts/LineChart/README.md
> +        key1: '6일차',
no Korean please!

2020-07-08 15:45 UTC, hyochan commented on packages/Charts/LineChart/types.ts
> +type YStyle = {
Add another space here would be clearer

2020-07-08 15:47 UTC, hyochan commented on packages/__tests__/LineChart.test.tsx
> +    key1: '6일차',
No Korean in tests either!

2020-07-08 15:47 UTC, hyochan commented on stories/packages/LineChart.stories.tsx
> +    key1: '6일차',
No Korean.

2020-07-08 15:48 UTC, hyochan requested changes
Looks good to be merged after fixing minor reviews! 👍

2020-07-08 15:48 UTC, hyochan commented on packages/Charts/LineChart/README.md
> +fontWeight: 'bold'
Indentation?

2020-07-08 15:49 UTC, hyochan commented on packages/Charts/LineChart/README.md
> +}
Indentation?

2020-07-09 00:45 UTC, filoscoder commented on packages/Charts/LineChart/README.md
> +        key1: '6일차',
got it!

2020-07-09 00:47 UTC, filoscoder commented on packages/Charts/LineChart/types.ts
> +type YStyle = {
You're right, got it!

2020-07-09 02:24 UTC, hyochan approved these changes
Next time please continue to commit to the same branches when reviewed.
Closed via #233

2020-07-09 02:24 UTC, merged