[WIP]Refactoring EditText
dooboolab/dooboo-ui-native pull request #234
Opened 2020-07-09 05:46 UTC by DevYuns

## Description

Refactoring EditText. I'll make that the code has more readability and Scalability.

## Tests

I added the following tests:

_Replace this with a list of the tests that you added as part of this PR. A change in behavior with no test covering it
will likely get reverted accidentally sooner or later. PRs must include tests for all changed/updated/fixed behaviors. See [Test Coverage](https://codecov.io/gh/dooboolab/dooboo-ui)._

## Checklist

Before you create this PR confirms that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide](https://github.com/dooboolab/dooboo-ui/blob/master/CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [ ] Run `yarn test` or `yarn test -u` if you need to update snapshot.
- [ ] Run `yarn lint`
- [x] I am willing to follow-up on review comments in a timely manner.

2020-07-09 13:08 UTC, hyochan requested changes
![image](https://user-images.githubusercontent.com/27461460/87043822-9dce8e80-c230-11ea-8613-9422e073234c.png)

I only see `default` where are other types??

2020-07-10 00:46 UTC, DevYuns commented
> ![image](https://user-images.githubusercontent.com/27461460/87043822-9dce8e80-c230-11ea-8613-9422e073234c.png)
> 
> I only see `default` where are other types??

I made default value only for code review. If It doesn't need any changes or improvement, I will make a more use case.

2020-07-10 05:32 UTC, hyochan commented
@DevYuns  Please request review when you think you are ready

2020-07-10 10:43 UTC, DevYuns commented
![EditText](https://user-images.githubusercontent.com/58724686/87146228-987f4b80-c2e5-11ea-8f66-1839aaeff574.gif)

2020-07-10 13:36 UTC, hyochan commented on main/EditText/README.md
> +            회원가입
No Korean~

2020-07-10 13:37 UTC, hyochan commented on main/EditText/README.md
> +              이메일이 유효하지 않습니다.
No Korean~

2020-07-10 13:37 UTC, hyochan requested changes
Please remove Korean & re-request review!

2020-07-13 01:41 UTC, hyochan approved these changes

2020-07-13 01:41 UTC, merged