[Button] Add mouse hover implement for Web
dooboolab/dooboo-ui-native pull request #237
Opened 2020-07-10 07:11 UTC by s-ong-c

## Description

Added mouse hover functional to button components
hover action works only on the web

<img width="381" alt="스크린샷 2020-07-10 오후 3 07 03" src="https://user-images.githubusercontent.com/34743425/87126873-eab17400-c2c7-11ea-9073-3369359172df.png">

## Checklist
Before you create this PR confirms that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide](https://github.com/dooboolab/dooboo-ui/blob/master/CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] Run `yarn test` or `yarn test -u` if you need to update snapshot.
- [x] Run `yarn lint`
- [x] I am willing to follow-up on review comments in a timely manner.

2020-07-10 07:31 UTC, hyochan commented on main/Button/README.md
> +    onPress={(): void => {}}>
I'd prefer the previous one!

2020-07-10 07:33 UTC, hyochan commented on main/Button/hooks/customHooks.ts
> +      const onEnd = resolve.bind(this, false);
Can we not use `bind` here?

2020-07-10 07:34 UTC, hyochan commented on main/Button/hooks/utils/getNode.ts
> +// @ts-ignore
findDomNode need `@ts-ignore`?

2020-07-10 07:35 UTC, hyochan commented on main/Button/index.tsx
> +  Accent?: ViewStyle;
We prefer not to use `Capital` letter with prop's name

2020-07-10 07:35 UTC, hyochan commented on main/Button/index.tsx
> +  Secondary?: ViewStyle;
Same here!

2020-07-10 07:36 UTC, hyochan requested changes
Please fix minor things in code convention.

2020-07-12 04:24 UTC, hyochan commented on main/Button/README.md
> +    >
The previous one is correct!

2020-07-12 04:24 UTC, hyochan commented on main/Button/README.md
> +    onPress={(): void => {}}>
Same here!

2020-07-12 04:25 UTC, hyochan commented on main/Button/README.md
> +    onPress={(): void => {}}>
Same here

2020-07-12 04:25 UTC, hyochan commented on main/Button/README.md
> +  </SampleButton>;
; ?

2020-07-12 04:25 UTC, hyochan commented on main/Button/README.md
> +  </SampleButton>;
; ?

2020-07-12 04:25 UTC, hyochan commented on main/Button/README.md
> +          onPress={() => {}}>
Previous one is correct!

2020-07-12 04:26 UTC, hyochan commented on main/Button/README.md
> +          }}>
Rollback please

2020-07-12 04:26 UTC, hyochan commented on main/Button/README.md
> +          }}>
Rollback please

2020-07-12 04:29 UTC, hyochan requested changes
Some of the changes in the `readme` are incorrect.

2020-07-12 11:03 UTC, s-ong-c commented
> Some of the changes in the `readme` are incorrect.

@hyochan In the my vscode prettierrc settings, I found that the semicolon and ">" Incorrect.
 So I fixed

2020-07-13 01:42 UTC, hyochan approved these changes
GJ. We need to think further where the custom hooks should be placed.

2020-07-13 01:42 UTC, merged