Change box type to show signIn style and add 1 props which is contentStyle
dooboolab/dooboo-ui-native pull request #264
Opened 2020-07-29 02:25 UTC by DevYuns

## Description

Change box type to show signIn style and add 1 props which is contentStyle.
I'm checking style on web, ios, android and storybook.
And I will update README.md file If this PR should be merged.

The new style shows below.
![image](https://user-images.githubusercontent.com/58724686/88749111-93e3df80-d18d-11ea-8c41-a0c5acada1b3.png)

## Checklist

Before you create this PR confirms that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide](https://github.com/dooboolab/dooboo-ui/blob/master/CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] Run `yarn test` or `yarn test -u` if you need to update snapshot.
- [x] Run `yarn lint`
- [x] I am willing to follow-up on review comments in a timely manner.

2020-07-29 02:38 UTC, DevYuns commented
Ci test failed because of other component test snapshot.

2020-07-29 11:27 UTC, hyochan commented
> Ci test failed because of other component test snapshot.

Nam Tat?

2020-07-29 11:32 UTC, hyochan requested changes
![image](https://user-images.githubusercontent.com/27461460/88795134-8143c780-d1da-11ea-8f63-79d43f95c2ee.png)

You only updated the `boxType`. Please fix others too. You can mostly participate on the colors.

2020-07-29 11:34 UTC, DevYuns commented
Ok I will

2020-07-29 14:26 UTC, hyochan commented
> Ok I will

When?

2020-07-30 05:38 UTC, DevYuns commented
I've try to change the` ternary operator` to `&&` operator in below image1 section, It induced errors in mobile. This errors can be occurred only about Text component in JSX. If someone wants to know further about this problem, check [here](https://github.com/facebook/react-native/issues/20764).  

image1
<img width="491" alt="Screen Shot 2020-07-30 at 11 05 17" src="https://user-images.githubusercontent.com/58724686/88884471-a0416880-d271-11ea-8431-03ef79a679f8.png">


Try
<img width="579" alt="Screen Shot 2020-07-30 at 11 05 43" src="https://user-images.githubusercontent.com/58724686/88884486-aafbfd80-d271-11ea-941f-5a7989add917.png">


Error message
<img width="371" alt="Screen Shot 2020-07-30 at 11 05 57" src="https://user-images.githubusercontent.com/58724686/88884492-b2230b80-d271-11ea-9766-3616e1def520.png">

2020-07-30 06:07 UTC, hyochan requested changes
Please re-request review when you are perfect

2020-07-30 08:03 UTC, hyochan requested changes
![image](https://user-images.githubusercontent.com/27461460/88897665-a1c95b80-d286-11ea-9fc4-b583f70414dd.png)

2020-07-30 13:57 UTC, hyochan commented on main/EditText/README.md
> +            testID="EMAIL_INPUT_DEFAULT"
Still not updated!

2020-07-30 13:57 UTC, hyochan commented on main/EditText/README.md
> +            testID="EMAIL_INPUT_DEFAULT"
Update the readme too!

2020-07-30 14:12 UTC, hyochan approved these changes

2020-07-30 14:13 UTC, merged