Updated Readme.md of Calendar Carousel
dooboolab/dooboo-ui-native pull request #308
Opened 2020-08-19 02:26 UTC by shljessie

## Description

_Replace this paragraph with a description of what this PR is doing. If you're modifying existing behavior, describe the existing behavior, how this PR is changing it, and what motivated the change. If you're changing visual properties, consider including before/after screenshots (and runnable code snippets to reproduce them)._

## Related Issues

_Replace this paragraph with a list of issues related to this PR from our [issue database]. Indicate, which of these issues are resolved or fixed by this PR._

## Tests

I added the following tests:

_Replace this with a list of the tests that you added as part of this PR. A change in behavior with no test covering it
will likely get reverted accidentally sooner or later. PRs must include tests for all changed/updated/fixed behaviors. See [Test Coverage](https://codecov.io/gh/dooboolab/dooboo-ui)._

## Checklist

Before you create this PR confirms that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x ] I read the [Contributor Guide](https://github.com/dooboolab/dooboo-ui/blob/master/CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
- [ x] Run `yarn test` or `yarn test -u` if you need to update snapshot.
- [ ] Run `yarn lint`
- [ x] I am willing to follow-up on review comments in a timely manner.

2020-08-19 02:30 UTC, shljessie commented
Pushed the updated version of the readMe.md in Calendar Carousel

Currently, yarn test fails at

Screen Shot 2020-08-19 at 11 24 14 AM

2020-08-19 04:24 UTC, hyochan commented on packages/CalendarCarousel/README.md
> +    </SafeAreaView>
Please fix their indentation

2020-08-19 04:24 UTC, hyochan commented on packages/CalendarCarousel/README.md
> +```	```
Two ```

2020-08-19 04:24 UTC, hyochan commented on packages/CalendarCarousel/README.md
> +      </View>
Move them left. There are too many empty spaces.

2020-08-19 04:30 UTC, shljessie commented on packages/CalendarCarousel/README.md
> +      </View>
fixed!

2020-08-20 07:47 UTC, hyochan commented on packages/CalendarCarousel/index.tsx
> +    return dateitem.getDate() === today.getDate() &&
`dateitem` => `dateItem`

2020-08-20 07:48 UTC, hyochan commented on packages/CalendarCarousel/index.tsx
> +    return d === selectedDate?.getDate() && month === selectedDate?.getMonth() && year === selectedDate?.getFullYear();
```
const isSelectedDate = d === selectedDate?.getDate() && month === selectedDate?.getMonth() && year === selectedDate?.getFullYear();

return isSelectedDate;
```

2020-08-20 07:49 UTC, hyochan commented on packages/CalendarCarousel/index.tsx
> +    return markedDates.includes(d) && markedMonths.includes(month) && markedYears.includes(year);
```
const hasCurrentDateMarked = markedDates.includes(d) && markedMonths.includes(month) && markedYears.includes(year);

return hasCurrentDateMarked;
```

2020-08-20 07:50 UTC, hyochan requested changes
Please add a meaningful variable name for the readability of the conditional statement is bit complex.

2020-08-20 08:01 UTC, shljessie commented
I can't do the isSelected and hasEvent changes you mentioned because I have to receive 'd' as a parameter! I did change the names of the functions for clarity though!

2020-08-22 08:28 UTC, hyochan commented on packages/CalendarCarousel/index.tsx
> +    const update = nextMonth;
New line before / after paragraph code.

2020-08-22 08:28 UTC, hyochan commented on packages/CalendarCarousel/index.tsx
> +    const lastDate = new Date(year, month + 1, 0).getDate();
No newline after the single line of code.

2020-08-22 08:29 UTC, hyochan commented on packages/CalendarCarousel/index.tsx
>      for (let idx = 0; idx < firstWeekday; idx++) {
Newline before paragraph code.

2020-08-22 08:29 UTC, hyochan commented on packages/CalendarCarousel/index.tsx
> +    for (let idx = 1; idx <= lastDate; idx++) {
Same here.

2020-08-22 08:29 UTC, hyochan commented on packages/CalendarCarousel/index.tsx
>      if (6 - lastWeekday >= 1) {
Here!

2020-08-22 08:30 UTC, hyochan commented on packages/CalendarCarousel/index.tsx
> +    }
You can remove `else` here and just return rest element.

2020-08-22 08:31 UTC, hyochan commented on packages/CalendarCarousel/index.tsx
> +    if (!layoutWidth || layoutWidth === 1) return;
Newline before / after `if` statement.

2020-08-22 08:32 UTC, hyochan requested changes
Much better @shljessie! Just a few more styling.

2020-08-24 14:51 UTC, hyochan commented on packages/CalendarCarousel/index.tsx
> +        {renderEventText()}
`renderEvent` since this is just and `element`!

2020-08-25 03:10 UTC, shljessie commented
made changes!

2020-08-25 03:54 UTC, shljessie commented
I found the function renderCalendars() that renders three Calendars to be unnecessary therefore, I created a function that erases that part.

2020-08-25 04:44 UTC, shljessie commented
I think I'll start preparing for the presentation tomorrow based on the code I have now! let me know if there are any more changes I should make.

2020-08-25 13:16 UTC, hyochan commented
![image](https://user-images.githubusercontent.com/27461460/91178711-7cfac380-e720-11ea-981f-aab4d5e33a45.png)

Where did the `intl` go?

Also renderCalendar() is not using `currentDate` so all 3 calendars look the same

2020-08-26 07:06 UTC, hyochan approved these changes
Great work on this @shljessie :100:

2020-08-26 07:08 UTC, merged