[WIP]Major refactoring [Accordion]
dooboolab/dooboo-ui-native pull request #321
Opened 2020-08-30 10:51 UTC by DevYuns

## Description

Change log
Remove Props
- accordionItemStyle
- titleStyle
- bodyStyle

Add Props
- renderCustomTitle
- renderCustomBody
- customTitleStyle
- customBodyStyle

Things to do 
[ ] change README.md
[ ] Update CHANGELOG.md
[ ] Add test code

## Related Issues

_Replace this paragraph with a list of issues related to this PR from our [issue database]. Indicate, which of these issues are resolved or fixed by this PR._

## Tests

## Checklist

Before you create this PR confirms that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide](https://github.com/dooboolab/dooboo-ui/blob/master/CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
- [ ] Run `yarn test` or `yarn test -u` if you need to update snapshot.
- [ ] Run `yarn lint`
- [x] I am willing to follow-up on review comments in a timely manner.

2020-08-30 10:54 UTC, DevYuns commented
@hyochan If you approve this changes, I'll updage test code, readme, changelog according to this changes.

2020-08-30 10:58 UTC, hyochan commented on main/Accordion/AccordionItem.tsx
> +  renderCustomBody?: (item: string) => React.ReactElement;
`renderTitle`, `renderBody`

2020-08-30 10:59 UTC, hyochan commented on main/Accordion/AccordionItem.tsx
> +  customBodyStyle?: ViewStyle;
`titleContainerStyle`, `bodyContainerStyle`

2020-08-30 10:59 UTC, hyochan commented on main/Accordion/AccordionItem.tsx
> +    );
```
return <StyldTitle>{title}</StyledTitle>
```

2020-08-30 11:01 UTC, hyochan requested changes

2020-08-30 11:01 UTC, hyochan commented on main/Accordion/AccordionItem.tsx
> +    );
Same as https://github.com/dooboolab/dooboo-ui/pull/321/files#r479754792

2020-08-30 11:01 UTC, hyochan commented on main/Accordion/AccordionItem.tsx
> +            : renderDefaultTitle(datum.title)
If you can change `datum` to `item`, it'd be better.

2020-08-30 11:01 UTC, hyochan commented on stories/dooboo-ui/Accordion.stories.tsx
> +    >
If there is only one prop underneath, this can be shortened to
```
<SafeAreaView style={{ top: 200 }} >
```

2020-08-30 11:34 UTC, hyochan requested changes
![image](https://user-images.githubusercontent.com/27461460/91657933-231f4280-eb00-11ea-8740-8f6450c81442.png)

2020-09-01 04:58 UTC, hyochan requested changes

2020-09-01 04:58 UTC, hyochan commented on main/Accordion/AccordionItem.tsx
> +  display: flex;
Please remove this. Every views are `flex` in `react-native`.

2020-09-01 04:58 UTC, hyochan commented on main/Accordion/AccordionItem.tsx
> +type toggleIndicatorType = React.ReactElement | undefined;
type should be `UpperCamelCase`.

2020-09-01 12:06 UTC, hyochan approved these changes
Much better!

2020-09-01 12:07 UTC, merged