[Feature] Datepicker Component
dooboolab/dooboo-ui-native pull request #332
Opened 2020-09-11 03:25 UTC by bumjoo

## Description

A Date picker component
* This component provide a simple way to select a date value from calendar popup.
* You can customize the year and month area on the calendar.
* You can set the type of day display. ('narrow' | 'short')

![dooboo_datepicker](https://user-images.githubusercontent.com/38123162/92732197-11b42100-f3b1-11ea-9c11-ac9dd7aec5e5.gif)

## Related Issues

#305 [Feature] DatePicker

## Tests

Simple rendering snapshot tests.

## Checklist

Before you create this PR confirms that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide](https://github.com/dooboolab/dooboo-ui/blob/master/CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
- [x] Run `yarn test` or `yarn test -u` if you need to update snapshot.
- [x] Run `yarn lint`
- [x] I am willing to follow-up on review comments in a timely manner.

2020-09-11 12:11 UTC, JeffGuKang requested changes
It looks very useful feature. 
I tested manually on iOS simulator and found minor issues. 
Just fix some codes following coding convention.

- New line before/after new paragraphs.
- Do not leave `console.log`
- English is default language for dooboo-ui.

2020-09-11 12:11 UTC, JeffGuKang commented on stories/dooboo-ui/DatePicker.stories.tsx
> +import { IC_FACEBOOK, IC_GOOGLE } from '../Icon';
Delete the line.

2020-09-11 12:11 UTC, JeffGuKang commented on stories/dooboo-ui/DatePicker.stories.tsx
> +  const [googleLoading, setGoogleLoading] = useState<boolean>(false);
It looks useless states.

2020-09-11 12:11 UTC, JeffGuKang commented on main/DatePicker/README.md
> +## Props
There are no descrpitions about `yearMonthComponent`, `weekdayFormat` and so on.

2020-09-11 12:11 UTC, JeffGuKang commented on main/DatePicker/README.md
> +```
Keep the clean MARKDOWN rule as https://raw.githubusercontent.com/dooboolab/dooboo-ui/master/main/PinchZoom/README.md.

2020-09-11 12:11 UTC, JeffGuKang commented on stories/dooboo-ui/DatePicker.stories.tsx
> +import { action } from '@storybook/addon-actions';
Useless import.

2020-09-11 12:11 UTC, JeffGuKang commented on stories/dooboo-ui/DatePicker.stories.tsx
> +import { text } from '@storybook/addon-knobs';
Useless import.

2020-09-11 12:11 UTC, JeffGuKang commented on main/DatePicker/README.md
> +|placeholderTextColor|      |string|            |
Please fix their indentation.

2020-09-11 12:11 UTC, JeffGuKang commented on main/DatePicker/index.tsx
> +  };
New line before paragraph code.

2020-09-11 12:11 UTC, JeffGuKang commented on stories/dooboo-ui/DatePicker.stories.tsx
> +}
New line before / after paragraph.

2020-09-11 12:11 UTC, JeffGuKang commented on stories/dooboo-ui/DatePicker.stories.tsx
> +};
New line before another paragraph.

2020-09-11 12:11 UTC, JeffGuKang commented on stories/dooboo-ui/DatePicker.stories.tsx
> +/**
New line before another paragraph.

2020-09-11 12:11 UTC, JeffGuKang commented on main/DatePicker/Calendar/Calendar.tsx
> +  containerStyle?: ViewStyle; // Calendar 컨테이너 스타일
Many users cannot understand Korean. Please all Korean translate to English.

2020-09-11 12:11 UTC, JeffGuKang commented on main/DatePicker/Calendar/Calendar.tsx
> +  futureRange?: number; // 미래 월 개월 수
Korean comments.

2020-09-11 12:11 UTC, JeffGuKang commented on main/DatePicker/Calendar/Calendar.tsx
> +  calendarWidth: number; // 달 표시 width
Korean.

2020-09-11 12:11 UTC, JeffGuKang commented on main/DatePicker/Calendar/Calendar.tsx
> + * - 일 컴포넌트는 dayComponent(function). props로 받음
Need to translate to English

2020-09-11 12:11 UTC, JeffGuKang commented on main/DatePicker/Calendar/Calendar.tsx
> +  // 금월 (시작월) 날짜
English please.

2020-09-11 12:11 UTC, JeffGuKang commented on main/DatePicker/Calendar/Calendar.tsx
> +  // 월 달력 그리기
English.

2020-09-11 12:11 UTC, JeffGuKang commented on main/DatePicker/Calendar/Calendar.tsx
> +      console.log('>> monthFirst = ', monthFirst);
Don't leave the console log.

2020-09-11 12:11 UTC, JeffGuKang commented on main/DatePicker/Calendar/Calendar.tsx
> +
Delete empty line for comments.

2020-09-11 12:11 UTC, JeffGuKang commented on main/DatePicker/Calendar/Calendar.tsx
> +}
New line.

2020-09-11 12:11 UTC, JeffGuKang commented on main/DatePicker/Calendar/Calendar.tsx
> +  yearMonthComponent?: (monthFirst: Date) => React.ReactElement;
`yearMonthComponent` is a little bit wired name. 
`titleContent?: (date: Date)` or `header?: (date: Date)` will be better.

2020-09-11 12:11 UTC, JeffGuKang commented on main/DatePicker/Calendar/Calendar.tsx
> +}
Need a new line.

2020-09-11 12:11 UTC, JeffGuKang commented on main/DatePicker/Calendar/Calendar.tsx
> +  });
const MemoizedCalendarMonth = React.memo(CalendarMonth) is same if you do not use custom comparison logic for rerender.

2020-09-11 12:11 UTC, JeffGuKang commented on main/DatePicker/Calendar/Calendar.tsx
> +  );
New line.

2020-09-11 12:11 UTC, JeffGuKang commented on main/DatePicker/Calendar/Calendar.tsx
> +  );
New line.

2020-09-11 12:11 UTC, JeffGuKang commented on main/DatePicker/Calendar/Calendar.tsx
> +  );
Empty line after paragraph code.

2020-09-11 12:11 UTC, JeffGuKang commented on main/DatePicker/Calendar/CalendarDate.tsx
> +  return (
Empty line before return.

2020-09-11 12:11 UTC, JeffGuKang commented on main/DatePicker/Calendar/CalendarDate.tsx
> +        props.onPress && props.onPress(props.date);
It is same with `props.onPress?.(props.date);` 👍

2020-09-11 12:11 UTC, JeffGuKang commented on main/DatePicker/Calendar/CalendarMonth.tsx
> +    isCurMonth,
`isCurrentMonth` is more readable.

2020-09-11 12:11 UTC, JeffGuKang commented on main/DatePicker/Calendar/CalendarDaysRow.tsx
> +`;
Need a new line.

2020-09-11 12:11 UTC, JeffGuKang commented on main/DatePicker/Calendar/CalendarDaysRow.tsx
> +`;
Need a new line.

2020-09-11 12:11 UTC, JeffGuKang commented on main/DatePicker/Calendar/CalendarDaysRow.tsx
> +`;
New line.

2020-09-11 12:11 UTC, JeffGuKang commented on main/DatePicker/Calendar/CalendarDaysRow.tsx
> +
Use English and merge comments.

2020-09-11 12:11 UTC, JeffGuKang commented on main/DatePicker/Calendar/CalendarDaysRow.tsx
> +  }
New line.

2020-09-11 12:11 UTC, JeffGuKang commented on main/DatePicker/Calendar/CalendarDaysRow.tsx
> +  for (let idx = 0; idx <= 6; idx++) {
New line.

2020-09-11 12:11 UTC, JeffGuKang commented on main/DatePicker/Calendar/CalendarMonth.tsx
> +  console.log('>>>> calendar width in CalendarMonth = ', props.calendarWidth);
Do not leave a console log for users.

2020-09-11 12:11 UTC, JeffGuKang commented on main/DatePicker/PickerCalendar.tsx
> +                      }월`}</Text>
Express with only numbers will be better for users as `2020.5`

2020-09-11 12:18 UTC, JeffGuKang commented
and `renderDay` is better than a `dayComponent` prop.

2020-09-11 12:22 UTC, JeffGuKang commented
Refer the parameter names: https://github.com/wix/react-native-calendars

2020-09-11 12:41 UTC, JeffGuKang commented
Test will be passed after increasing coverage more.

2020-09-11 13:43 UTC, bumjoo commented on main/DatePicker/Calendar/Calendar.tsx
> +  });
I think it's not same.
This is to ensure that the component does not change even when all props are changed.

2020-09-12 03:27 UTC, JeffGuKang commented
Good! Do not forget update snapshots.

2020-09-13 06:29 UTC, JeffGuKang approved these changes

2020-09-13 06:46 UTC, JeffGuKang commented on .vscode/settings.json
> +  "editor.formatOnSave": true,
This should be removed because it is a file that has nothing to do with this PR.

2020-09-13 06:50 UTC, JeffGuKang approved these changes
Great job! 
I will add a issue `Datepicker` feature to cover web environment.

2020-09-13 06:50 UTC, JeffGuKang commented on .vscode/settings.json
> +  "editor.formatOnSave": true,
I will fix it so don't care about it.

2020-09-13 06:53 UTC, merged