Bugfix/remove linter erros
dooboolab/dooboo-ui-native pull request #339
Opened 2020-09-13 08:11 UTC by greatSumini

## Description

remove linter errors, update snapshots for Badge, DatePicker component

## Related Issues

x

## Tests

I added the following tests:

x

## Checklist

Before you create this PR confirms that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide](https://github.com/dooboolab/dooboo-ui/blob/master/CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
- [x] Run `yarn test` or `yarn test -u` if you need to update snapshot.
- [x] Run `yarn lint`
- [x] I am willing to follow-up on review comments in a timely manner.

2020-09-13 08:27 UTC, JeffGuKang requested changes
`DatePicker` is waiting the PR related to #337. So how about dealing with only Badges here?

2020-09-13 08:27 UTC, JeffGuKang commented on main/Badge/index.tsx
> +
Meaningless empty line.

2020-09-13 08:27 UTC, JeffGuKang commented on main/Badge/index.tsx
Remove empty line.

2020-09-13 14:21 UTC, greatSumini commented
> `DatePicker` is waiting the PR related to #337. So how about dealing with only Badges here?

Sounds great! i reverted commits about DatePicker

2020-09-13 14:21 UTC, greatSumini commented on main/Badge/index.tsx
> +
thk u for comment! resolved in 4330880

2020-09-13 14:21 UTC, greatSumini commented on main/Badge/index.tsx
resolved in 4330880

2020-09-18 12:21 UTC, JeffGuKang commented
Could you update README? Cause `position` should be replaced by `badgePlacement`.

2020-09-19 12:24 UTC, greatSumini commented
> @greatSumini Good! Could you update a doc? Cause `position` should be replaced by `badgePlacement`.

resolved in 62b32b7 😄

2020-09-20 02:44 UTC, JeffGuKang approved these changes

2020-09-20 02:49 UTC, merged