[Feature][Branch] Add AutoComplete Render Options
dooboolab/dooboo-ui-native pull request #72
Opened 2019-12-10 01:48 UTC by imjihun

## Description

- add background highlight when touched
- set value for Render Input when selected

## Related Issues

#50 

## Tests

none yet.

## Checklist

- [x] I read the [Contributor Guide](https://github.com/dooboolab/dooboo-ui-native/blob/master/CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] Run `yarn test` or `yarn test -u` if you need to update snapshot.
- [x] Run `yarn lint`
- [x] I am willing to follow-up on review comments in a timely manner.

2019-12-10 15:21 UTC, hyochan commented
@marsinearth Please review the beautiful work given.

2019-12-15 16:39 UTC, marsinearth requested changes
please make modifications

2019-12-15 16:39 UTC, marsinearth commented on src/components/shared/AutoComplete/index.tsx
> +    setSelectedData(data);
it seems `const [selectedData, setSelectedData] = useState<DummyDatum>();` can substitute `const [innerValue, setInnerValue] = useState<string>(value);` completely. Can you manage the related logic?

2019-12-15 17:09 UTC, marsinearth commented
<img src="https://user-images.githubusercontent.com/6101260/70866118-fdb9cb00-1fa8-11ea-9d24-652da43498fd.png" alt="circle-ci-ts-failure" width="300" />
and please solve this Circle CI typescript error, too.

2019-12-30 09:00 UTC, marsinearth approved these changes

2019-12-31 02:05 UTC, merged