[Feature][Branch][Rating] Refactoring and add README file
dooboolab/dooboo-ui-native pull request #81
Opened 2019-12-11 06:56 UTC by devohno

## Description

Updated [Rating] component and add README file

## Related Issues

#53 

## Tests

Not yet

## Checklist

Before you create this PR confirms that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide](https://github.com/dooboolab/dooboo-ui-native/blob/master/CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [ ] Run `yarn test` or `yarn test -u` if you need to update snapshot.
- [x] Run `yarn lint`
- [x] I am willing to follow-up on review comments in a timely manner.

2019-12-15 03:22 UTC, JeffGuKang requested changes
Normally, `onPress: () => void` or `onPress: (value: index) => void` styles are preferred when I define function parameter in interface instead of `Function`. It can be used as `onPress(): void` also. 

Ref: https://medium.com/@jeffbutsch/typescript-interface-functions-c691a108e3f1

2019-12-15 03:22 UTC, JeffGuKang commented on src/components/shared/Rating/index.tsx
> +  const initStars = new Array(props.total).fill(false);
How about to use `useMemo` for performance improvement?

2019-12-15 03:58 UTC, devohno commented on src/components/shared/Rating/index.tsx
> +  const initStars = new Array(props.total).fill(false);
OK. I'll try it

2019-12-15 12:56 UTC, JeffGuKang requested changes
Almost done! Cheer up.

2019-12-15 12:56 UTC, JeffGuKang commented on src/components/shared/Rating/index.tsx
> +  onChange?: (props: OnchangeProps) => void;
I think `(value: number) => void` is enough for type.

2019-12-15 12:56 UTC, JeffGuKang commented on src/components/shared/Rating/index.tsx
> +    props.onChange && props.onChange({ value: position + 1 });
If you change your `onChange` prop to `onChnage: (value: number) => void`, 
`onChange(position + 1)` will be match your type predifined.

2019-12-16 02:37 UTC, JeffGuKang commented
@devohno Pass the test by updating snapshot.

2019-12-16 04:52 UTC, JeffGuKang approved these changes

2019-12-16 04:52 UTC, merged