[Feature][Branch][RadioButton] Update test code
dooboolab/dooboo-ui-native pull request #85
Opened 2019-12-11 09:58 UTC by Saehanseul

## Description

Add test code for RadioButton

## Related Issues

#51

## Tests

I added the following tests:

Test render, onPress and props.
Coverage 100% completed.

## Checklist

2019-12-11 12:39 UTC, JeffGuKang commented
Resolve semicolon and blank issue caught by lint test. [link](https://circleci.com/gh/dooboolab/dooboo-ui-native/324?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

2019-12-11 12:47 UTC, JeffGuKang commented
And it will be better to use same user information for git and GitHub. :)

2019-12-12 04:11 UTC, devethan requested changes

2019-12-12 04:11 UTC, devohno commented on src/components/shared/__tests__/RadioButton.test.tsx
> +    })
Missing semicolon here

2019-12-13 15:22 UTC, JeffGuKang approved these changes

2019-12-13 15:22 UTC, merged