[Feature][Branch][Rating] Update test code
dooboolab/dooboo-ui-native pull request #98
Opened 2019-12-21 09:48 UTC by Saehanseul

## Description
Update rating test code.

## Related Issues
#53

## Tests
I added the following tests:

Test render, onPress and props.
Coverage 100% completed.

2019-12-22 15:41 UTC, devohno commented on src/components/shared/__tests__/Rating.test.tsx
> +const component = (props?): React.ReactElement => {
I think `props` should be follow [this interface rule](https://github.com/dooboolab/dooboo-ui-native/blob/f52dd3d302ab3135490681e99a3a8409ba0fd9ba/src/components/shared/Rating/index.tsx#L5)

`total` and `value` should be included.

2019-12-22 15:41 UTC, devohno commented on src/components/shared/__tests__/Rating.test.tsx
>  let props: any;
How about this.
```
interface Props {
  total: number;
  value: number;
  onChange?: (value: number) => void;
  disabled?: boolean;
}

let props: Props;
```

and then

```
let component: ReactElement;

component = <Rating {...props} />
```

2019-12-29 06:09 UTC, JeffGuKang requested changes
@devohno Thanks to review and good point about to use `any` type. 
I asked about this issue to the maintainer and they said using `any` props for test components is better than define specific types.

2019-12-29 06:10 UTC, JeffGuKang approved these changes

2019-12-29 06:10 UTC, merged